services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Disable HTTPS if needed
      SERVER_NAME: ":80"
      # Add JWT keys
      MERCURE_PUBLISHER_JWT_KEY: "secret-key"
      MERCURE_SUBSCRIBER_JWT_KEY: "secret-key"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        cors_allowed_headers "Content-Type,Authorization"
        cors_exposed_headers "Link"
        cors_credentials on
        anonymous
        publish_origins *
        demo
