services:
  - type: web
    name: mercure-hub
    env: docker
    plan: free
    envVars:
      - key: MERCURE_PUBLISHER_JWT_KEY
        value: "!myPublisherSecret!"
      - key: MERCURE_SUBSCRIBER_JWT_KEY
        value: "!mySubscriberSecret!"
